services:
  db:
    hostname: db
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=swiss-law-gpt
      - POSTGRES_USER=pg-law
      - POSTGRES_PASSWORD=pg-law
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
